defaults: &defaults
  docker:
  - image: golang:1.12
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
    - checkout
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

  verify:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make verify

  checkfmt:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make checkfmt

  lint:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make tools lint

  test:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make test

  build:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: make build
    - save_cache:
        key: cca-{{ .Revision }}
        paths:
        - /go/src/github.com/cloud-ca/cca

workflows:
  version: 2
  build:
    jobs:
    - checkout:
        filters:
          tags:
            only: /v.*/
    - verify:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
    - checkfmt:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
    - lint:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
    - test:
        requires:
        - checkout
        filters:
          tags:
            only: /v.*/
    - build:
        requires:
        - verify
        - checkfmt
        - lint
        - test
        filters:
          tags:
            only: /v.*/
