// Automatically generated by MockGen. DO NOT EDIT!
// Source: configuration/configuration.go

package configuration_mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of ConfigurationService interface
type MockConfigurationService struct {
	ctrl     *gomock.Controller
	recorder *_MockConfigurationServiceRecorder
}

// Recorder for MockConfigurationService (not exported)
type _MockConfigurationServiceRecorder struct {
	mock *MockConfigurationService
}

func NewMockConfigurationService(ctrl *gomock.Controller) *MockConfigurationService {
	mock := &MockConfigurationService{ctrl: ctrl}
	mock.recorder = &_MockConfigurationServiceRecorder{mock}
	return mock
}

func (_m *MockConfigurationService) EXPECT() *_MockConfigurationServiceRecorder {
	return _m.recorder
}

func (_m *MockConfigurationService) Get(id string, options map[string]string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Get", id, options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigurationServiceRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0, arg1)
}

func (_m *MockConfigurationService) List(options map[string]string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "List", options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigurationServiceRecorder) List(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "List", arg0)
}

func (_m *MockConfigurationService) Create(body []byte, options map[string]string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Create", body, options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigurationServiceRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Create", arg0, arg1)
}

func (_m *MockConfigurationService) Update(id string, body []byte, options map[string]string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Update", id, body, options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigurationServiceRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Update", arg0, arg1, arg2)
}

func (_m *MockConfigurationService) Delete(id string, body []byte, options map[string]string) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Delete", id, body, options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockConfigurationServiceRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0, arg1, arg2)
}
